Wishlist promotion task
m4thayus/quicksilver pull request #19
Opened 2022-10-25 20:59 UTC by scottb

Adds a rake task to promote approved wishlist tasks to the main board.

Removes the `before_save` hook to clear the approved status; this is handled by the rake task.

Upgrades the sqlite3 gem to make `bundle-audit` happy. Disables `audit` in lefthook because it's too aggressive.

2022-10-25 21:17 UTC, zoeblairfriedman requested changes
With this change, if you move a task through the UI from one board to another, the approved status will not be cleared—this is misleading as the "approved" value means different things on our two different boards. "Approved by Ron" to be tackled on the wishlist vs "Reviewed" on the default board. Can we either add something back in that resets the value on a board change or remove the ability to change boards from the UI?

2022-10-25 22:18 UTC, scottb commented
I've modified the update path in the tasks controller to clear the approved flag if the board changes, and the flag isn't explicitly changed on the form. There's a new spec in `spec/requests/task_spec.rb` that verifies this functionality.

2022-10-26 14:39 UTC, zoeblairfriedman commented on spec/requests/tasks_spec.rb
> +      let(:params) { { task: { title: "new title" } } }
Are these params necessary? They make the test a little confusing.

2022-10-26 14:40 UTC, zoeblairfriedman approved these changes
Approved with one suggestion

2022-10-26 15:44 UTC, m4thayus approved these changes

2022-10-26 15:49 UTC, merged